forward_velocity:
  slope: -3.0
  weight: 1.0
lateral_velocity:
  slope: -3.0
  weight: 1.0
angular_velocity:
  slope: -1.5
  weight: 1.5

joint_position_tracking:
  weight: 1
  alpha: 2.0
joint_velocity_tracking:
  weight: 0.3
  alpha: 0.1
root_position_tracking:
  weight: 0.3
  alpha: 10.0
end_effector_tracking:
  weight: 0.5
  alpha: 30.0
  end_effector_links:
   - "right_wrist_yaw_link"
   - "left_wrist_yaw_link"
   - "right_ankle_pitch_link"
   - "left_ankle_pitch_link"