scene:
  num_envs: 1
  rows: 1
  cols: 1
  env_spacing: 30.0
  joint_names:
    # Torso/Abdomen joints (3 DOF)
    - 'abdomen_x'
    - 'abdomen_y'
    - 'abdomen_z'
    # Neck joints (3 DOF) - NEW in this model
    - 'neck_x'
    - 'neck_y'
    - 'neck_z'
    # Right arm joints
    - 'right_shoulder_x'
    - 'right_shoulder_y'
    - 'right_shoulder_z'
    - 'right_elbow'
    # Left arm joints
    - 'left_shoulder_x'
    - 'left_shoulder_y'
    - 'left_shoulder_z'
    - 'left_elbow'
    # Right leg joints (hip)
    - 'right_hip_x'
    - 'right_hip_y'
    - 'right_hip_z'
    - 'right_knee'
    # Left leg joints (hip)
    - 'left_hip_x'
    - 'left_hip_y'
    - 'left_hip_z'
    - 'left_knee'
    # Ankle joints (3 DOF each)
    - 'right_ankle_x'
    - 'right_ankle_y'
    - 'right_ankle_z'
    - 'left_ankle_x'
    - 'left_ankle_y'
    - 'left_ankle_z'
  body_contact_links:
    # Note: Verify these body names by printing env.scene["steve"].data.body_names
    - torso
    - head
    - abdomen
    - pelvis
    - right_upper_arm
    - left_upper_arm
    - right_lower_arm
    - left_lower_arm
    - right_thigh
    - left_thigh
    - right_hand
    - left_hand
    - right_shin
    - left_shin
    - right_foot
    - left_foot
env_config:
  sim_dt: 0.001
  decimation: 10
  max_episode_length: 1000
  episode_length_s: 10
  seed: 42
train:
  num_envs: 4096
  num_iterations: 400
  rows: 10
  cols: 10
  total_timesteps: 98e6
  n_steps: 128
  batch_size: 65_536
  learning_rate:
    start: 3.5e-4
    end: 3.0e-4
    end_fraction: 1.0
  clip_range: 0.2
  gamma: 0.992
  ent_coef: 0.0025
  n_epochs: 10
  target_kl: 0.015
eval:
  num_envs: 1
  rows: 1
  cols: 1

save_config:
  save_path: ../../models/isaac_models/
  save_prefix: ruu_ppo_model
