scene:
  num_envs: 1
  rows: 1
  cols: 1
  env_spacing: 30.0
  joint_names:
    - 'left_hip_yaw'
    - 'right_hip_yaw'
    - 'torso'
    - 'left_hip_roll'
    - 'right_hip_roll'
    - 'left_shoulder_pitch'
    - 'right_shoulder_pitch'
    - 'left_hip_pitch'
    - 'right_hip_pitch'
    - 'left_shoulder_roll'
    - 'right_shoulder_roll'
    - 'left_knee'
    - 'right_knee'
    - 'left_shoulder_yaw'
    - 'right_shoulder_yaw'
    - 'left_ankle'
    - 'right_ankle'
    - 'left_elbow'
    - 'right_elbow'
  body_contact_links:
    - pelvis
    - left_hip_yaw_link
    - right_hip_yaw_link
    - torso_link
    - left_hip_roll_link
    - right_hip_roll_link
    - left_shoulder_pitch_link
    - right_shoulder_pitch_link
    - left_hip_pitch_link
    - right_hip_pitch_link
    - left_shoulder_roll_link
    - right_shoulder_roll_link
    - left_knee_link
    - right_knee_link
    - left_shoulder_yaw_link
    - right_shoulder_yaw_link
    - left_elbow_link
    - right_elbow_link

env_config:
  sim_dt: 0.001
  decimation: 10
  max_episode_length: 1000
  episode_length_s: 10
  seed: 42
train:
  num_envs: 4096
  num_iterations: 600
  rows: 10
  cols: 10
  total_timesteps: 98e6
  n_steps: 64
  batch_size: 65_536
  learning_rate:
    start: 3.5e-4
    end: 3.5e-4
    end_fraction: 1.0
  clip_range: 0.2
  gamma: 0.992
  ent_coef: 0.0025
  n_epochs: 10
  target_kl: 0.07
eval:
  num_envs: 1
  rows: 1
  cols: 1

save_config:
  save_path: ../../models/isaac_models/
  save_prefix: ruu_ppo_model
