forward_velocity:
  slope: -3.0
  weight: 1.0
lateral_velocity:
  slope: -3.0
  weight: 1.0
angular_velocity:
  slope: -1.5
  weight: 1.5
balance:
  vz_slope: -2.5
  wxy_slope: -2.0
  weight: 1.3
joint_position_tracking:
  weight: 1
joint_velocity_tracking:
  weight: 0.1
root_orientation_tracking:
  weight: 0.1